version: 2.1

commands:
  desctroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      # Add parameters here
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: /
            # Your code here
            exit 1

  revert-migration:
    description: Revert the last migration if successfully run in current workflow.
    parameters:
      # Add parameter here
    steps:
      - run:
          name: Revert migrations
          # Add when this will run
          command: /
            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
            SUCCESS = 1
            if(( $SUCCESS==1 )); 
            then
            #  cd ~/project/backend
            #  npm install
            #  Add revert code here. You can find this in the Getting Started section.
              exit 1
            fi

jobs:
  build_frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build frontend
          command: /
            # Your code here
            exit 1
      - save_cache:
          paths: [frontend/node_modules]
          keys: frontend-build
